tws:
  image: ryankennedyio/ib-docker
  ports:
    - "4003:4003"
    - "5900:5900"
  volumes:
    - ./IBController.ini:/root/IBController/IBController.ini
    - ./jts.ini:/root/Jts/jts.ini
  environment:
    # Variables pulled from /IBController/IBControllerGatewayStart.sh
    - VNC_PASSWORD=password
    - TWS_MAJOR_VRSN=959
    - IBC_INI=/root/IBController/IBController.ini
    - TRADING_MODE=
    - IBC_PATH=/opt/IBController
    - TWS_PATH=/root/Jts
    - TWS_CONFIG_PATH=/root/Jts
    - LOG_PATH=/opt/IBController/Logs
    - TWSUSERID=edemo
    - TWSPASSWORD=demouser
    - FIXUSERID=
    - FIXPASSWORD=
    - JAVA_PATH=
    - APP=GATEWAY
